### ISSUE TITLE
Controller class not found

### ISSUE THREAD

**Issue by Bird87ZA** [dakota/CakeExcel#14]
I have everything set up as per the README file.

I've copied and pasted the `config/bootstrap.php` and `config/routes.php` lines. In my `AppController.php` file I have set up the `RequestHandler` component as required and I have a default template in `Template\Layout\xlsx\default.ctp` containing the one line as suggested.

I added the link (`$this->Html->link('Excel file', ['_ext' => 'xlsx'])` the controller's `index.ctp` file, and I have a `xlsx\index.ctp` file in the Template directory. When I load the page, the link is echo'd as `localhost\site\example.xlsx` where controller is the name of the controller. Clicking on this, it gives me a `Controller class Example.xlsx could not be found.` error. When I type the URL `localhost\site\example\index.xlsx` in the address bar, I get `Error: Create ExampleController::index.xlsx() in file: src\Controller\ExampleController.php.` error.

What am I doing wrong?

**Comment by josegonzalez** [comment]
@Bird87ZA how did you load the plugin?

**Comment by Bird87ZA** [comment]
Installed it with composer. and then in bootstrap.php I have this line:

`Plugin::load('CakeExcel', ['bootstrap' => true, 'routes' => true]);`

**Comment by Bird87ZA** [comment]
https://gist.github.com/Bird87ZA/2cd58b3251e7448d3a405d8684663a23

**Comment by josegonzalez** [comment]
Move the `Router::extensions('xlsx')` call to here: https://gist.github.com/Bird87ZA/2cd58b3251e7448d3a405d8684663a23#file-routes-php-L43

**Comment by Bird87ZA** [comment]
Works now. Thanks! :) Perhaps just add that in the Readme. :)
