### ISSUE TITLE
Upgrade to recent version of cakephp and PhpSpreadsheet

### ISSUE THREAD

**Issue by rochamarcelo** [dakota/CakeExcel#17]
There is any plan to upgrate this plugin to use recent version of cakephp and PhpSpreadsheet? PHPExcel is  no longer maintained.

Thanks

**Comment by josegonzalez** [comment]
@rochamarcelo would you be willing to submit a pull request?

**Comment by rochamarcelo** [comment]
Yes I would.

**Comment by josegonzalez** [comment]
Note: this library already supports phpspreadsheet: https://github.com/robotusers/cakephp-excel

**Comment by rochamarcelo** [comment]
But that library is more to be used as ORM
