### ISSUE TITLE
Get Hello World

### ISSUE THREAD

**Issue by artnos** [dakota/CakeExcel#6]
Hi is this plugin working? I noticed it says build failing in 3.0 Branch and the PHPExcel link it says build failing as well. And is this PHPExcel that your using the same as this one?
https://phpexcel.codeplex.com/

I am having trouble getting some kind of hello world to start
I did the composer

//bootstrap.php
Plugin::load('Dakota/CakeExcel', ['bootstrap' => true, 'routes' => true]); 

//appcontroller.php - in initialize()
 $this->loadComponent('RequestHandler',[
                    'viewClassMap' => [ 'xlsx' => 'CakeExcel.Excel' ]
                 ]
        );

//created a link, Template/Products/index.ctp
this->Html->link('Excel file', array('ext' => 'xlsx'));

//in my Template/Products/xlsx/index.ctp
<?php

$spreadsheet = $this->PhpExcel;
$spreadsheet->setActiveSheetIndex(0);
$worksheet = $spreadsheet->getActiveSheet();
$worksheet->SetCellValueByColumnAndRow(0, 1, 'Hello World');

$writer = new PHPExcel_Writer_Excel2007($spreadsheet);
$writer->save('hello-world.xlsx');

?>
//how do i get the php writer? How does it know to open index.ctp in that folder?

label:question

**Comment by josegonzalez** [comment]
I've update the docs and released a 3.x version.
